import { Grid, Typography, Button } from "@mui/material";
import Link from "next/link";
import MuiLink from "@mui/material/Link";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import style from "../styles/Textglobal.module.css";
import Routes from "src/constants/routes";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Poli Huellas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <Grid container spacing={6}>
            <Grid item xs={6}>
              <Image
                src="/images/pol1.png"
                alt="Picture of pets"
                width="1000px"
                height="500px"
              />
              <Grid item xs={12}>
                <Grid item xs={12}>
                  <Typography variant="subtitle1" sx={{ marginY: 2 }}>
                    Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                    Exercitationem, ipsum architecto? Accusamus vitae pariatur
                    quae eius alias omnis placeat quo?
                  </Typography>
                  <Link href={Routes.REGISTER} passHref>
                    <Button size="large" variant="contained" color="secondary">
                      Registrate
                    </Button>
                  </Link>
                </Grid>
              </Grid>
            </Grid>
            <Grid item xs={6}>
              <Image
                src="/images/pet44.png"
                alt="Picture of pets"
                width="1200px"
                height="900px"
              />
            </Grid>
            <Grid sx={{ marginTop: 10 }} item xs={12}>
              <Typography variant="h3" className={styles.title}>
                ¿Quieres <span className={styles.txtcolor}>adoptar</span> una
                mascota ?{" "}
              </Typography>
            </Grid>
            <Grid item xs={4}>
              <Image
                className={styles.img}
                src="/images/cat1.png"
                alt="Picture of pets"
                width="400px"
                height="400px"
              />
              <Link href={Routes.CATS} passHref>
                <MuiLink>
                  <h1 className={styles.title}>Gatos</h1>
                </MuiLink>
              </Link>
            </Grid>
            <Grid item xs={4}>
              <Image
                className={styles.img}
                src="/images/dog1.jpg"
                alt="Picture of pets"
                width="400px"
                height="400px"
              />
              <Link href={Routes.DOGS} passHref>
                <MuiLink>
                  <h1 className={styles.title}>Perros</h1>
                </MuiLink>
              </Link>
            </Grid>

            <Grid item xs={4}>
              <Image
                className={styles.img}
                src="/images/hamster.jpg"
                alt="Picture of pets"
                width="400px"
                height="400px"
              />
              <Link href={Routes.OTHER} passHref>
                <MuiLink>
                  <h1 className={styles.title}>Otros</h1>
                </MuiLink>
              </Link>
            </Grid>
            <Grid sx={{ marginTop: 4 }} item xs={6}>
              <Typography variant="h4">
                Encuentra un <span className={styles.txtcolor}>amigo</span> de
                compañia
              </Typography>
              <Typography sx={{ marginY: 5 }}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Officiis facilis magnam ratione, voluptas excepturi quos quo
                consequatur iusto dignissimos laudantium possimus ab ducimus
                quasi eveniet? Exercitationem, maiores? Autem quidem corporis,
                officiis hic iste quod et earum doloremque incidunt a
                asperiores?
              </Typography>
              <Link href={Routes.ADOPTIONS} passHref>
                <Button variant="contained" color="secondary">
                  Buscar mascota
                </Button>
              </Link>
            </Grid>
            <Grid sx={{ marginTop: 10 }} item xs={6}>
              <Image
                src="/images/huella2.png"
                alt="Picture of pets"
                width="400px"
                height="150px"
              />
            </Grid>

            <Grid sx={{ marginTop: 10 }} item xs={12}>
              <Typography variant="h3" className={styles.title}>
                ¿Porqué <span className={styles.txtcolor}>adoptar</span> es
                importante?
              </Typography>
            </Grid>
            <Grid c>
              <Typography sx={{ margin: 6 }}>
                Contrary to popular belief, Lorem Ipsum is not simply random
                text. It has roots in a piece of classical Latin literature from
                45 BC, making it over 2000 years old. Richard McClintock, a
                Latin professor at Hampden-Sydney College in Virginia, looked up
                one of the more obscure Latin words, consectetur, from a Lorem
                Ipsum passage, and going through the cites of the word in
                classical literature, discovered the undoubtable source. Lorem
                Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus
                Bonorum et Malorum"
              </Typography>
            </Grid>
          </Grid>
          <Grid className={styles.imgPos} item xs={12}>
            <Image
              src="/images/pet4.png"
              alt="Picture of pets"
              width="500px"
              height="400px"
            />
          </Grid>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
